controller_manager:
  ros__parameters:
    update_rate: 50  # hertz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.7
    wheel_radius: 0.127

    # Limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        min_velocity: -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0  # rad/s
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0