Teleop_Control Class Reference
Private Member Functions
void wait_for_state_manager ()
Halts teleop control until state manager fully completes the `bringup`/robot initialization step. Honestly probably too redundant & not necessary.
void set_param (const std::string &param_name, bool new_val)
Sets the param argument to the intended new boolean value.
void prep_robot ()
Initializes Robot XBOX Teleoperation Control parameters, so the single source of truth(state_mananger.cpp) publishes them.
void config_motor (SparkMax &motor)
Configures NEO BLDC Motors.
void configure_all_motors ()
Self-explanatory.
void callback_ps4 (const msg_Bool &state_PS4)
Saves the currently publishing PS4 state param to this file's LOCAL state.
void callback_xbox (const msg_Bool &state_XBOX)
Saves the currently publishing XBOX state param to this file's LOCAL state.
void callback_robot_enabled (const msg_Bool &state_robot_disabled)
Saves the currently publishing robot_disabled state param to this file's LOCAL state.
void callback_manual_enabled (const msg_Bool &state_manual_enabled)
Saves the currently publishing manual_enalbed state param to this file's LOCAL state.
void callback_outdoor_mode (const msg_Bool &state_outdoor_mode)
Saves the currently publishing outdoor_mode state param to this file's LOCAL state.
void callback_motor_heartbeat ()
Periodically sends a heartbeat signal to keep all SPARK controllers active.
void callback_joy (const JoyMsg msg)
Callback that interprets XBOX controller joystick input.
void callback_cmd_vel (const geometry_msgs::msg::Twist::SharedPtr velocity_msg)
Callback that calculates velocity commands to give the 4 Drivebase robot motors.
void parse_controller_input (const JoyMsg &msg)
Sets XBOX controller joystick input, so this file can use it locally.
int get_button (const JoyMsg &joy_msg, const std::initializer_list< int > &mappings)
Get the button pressed by XBOX Controller.
double get_axis (const JoyMsg &joy_msg, const std::initializer_list< int > &mappings)
Get the axis of button pressed.
void handle_mode_switches ()
Sets/notifies source of truth(state_manager.cpp) that we want Teleop Mode or Autonomous Mode. If Autonomous mode, no teleoperation should function.
void control_robot ()
Emergency Stop functions.
void control_drive ()
Teleop Drivebase Control.
void control_mining ()
Teleop Mining Control.
void control_dumping ()
Teleop Dumping control.
Private Attributes
rclcpp::Client< std_srvs::srv::Trigger >::SharedPtr ready_client
SetParameterClientSharedPtr param_client
BoolSubscriber sub_xbox
BoolSubscriber sub_robot_enabled
BoolSubscriber sub_manual_enabled
BoolSubscriber sub_outdoor_mode
BoolSubscriber sub_ps4
rclcpp::TimerBase::SharedPtr timer
TwistSubscription velocity_subscriber
JoySubscription joy_sub
ROBOT_ACTUATION_t robot_actuation
XBOX_JOYSTICK_INPUT_t xbox_input
ROBOTSTATE_t robot_state
ROBOT_LIMITS_t robot_dimensions
Member Function Documentation
callback_cmd_vel()
void Teleop_Control::callback_cmd_vel (const geometry_msgs::msg::Twist::SharedPtr velocity_msg) [inline], [private]
Callback that calculates velocity commands to give the 4 Drivebase robot motors.
Todo
Todo Is the call to SparkMax::Heartbeat() needed or can I delete it?
Parameters
velocity_msg
callback_joy()
void Teleop_Control::callback_joy (const JoyMsg msg) [inline], [private]
Callback that interprets XBOX controller joystick input.
Parameters
msg
References control_robot(), handle_mode_switches(), and parse_controller_input().
callback_manual_enabled()
void Teleop_Control::callback_manual_enabled (const msg_Bool & state_manual_enabled) [inline], [private]
Saves the currently publishing manual_enalbed state param to this file's LOCAL state.
Parameters
state_manual_enabled
callback_outdoor_mode()
void Teleop_Control::callback_outdoor_mode (const msg_Bool & state_outdoor_mode) [inline], [private]
Saves the currently publishing outdoor_mode state param to this file's LOCAL state.
Parameters
state_outdoor_mode
callback_ps4()
void Teleop_Control::callback_ps4 (const msg_Bool & state_PS4) [inline], [private]
Saves the currently publishing PS4 state param to this file's LOCAL state.
Parameters
state_PS4
callback_robot_enabled()
void Teleop_Control::callback_robot_enabled (const msg_Bool & state_robot_disabled) [inline], [private]
Saves the currently publishing robot_disabled state param to this file's LOCAL state.
Parameters
state_robot_disabled
callback_xbox()
void Teleop_Control::callback_xbox (const msg_Bool & state_XBOX) [inline], [private]
Saves the currently publishing XBOX state param to this file's LOCAL state.
Parameters
state_XBOX
config_motor()
void Teleop_Control::config_motor (SparkMax & motor) [inline], [private]
Configures NEO BLDC Motors.
Todo
Todo Make a version of this function for the smaller NEO motors, unless they are also BLDC;I havent checked.
Parameters
motor
Referenced by configure_all_motors().
configure_all_motors()
void Teleop_Control::configure_all_motors () [inline], [private]
Self-explanatory.
Todo
Todo If the smaller NEO motors are NOT BLDC, use their version of config_motor() inside this function
References config_motor().
control_drive()
void Teleop_Control::control_drive () [inline], [private]
Teleop Drivebase Control.
Todo
Todo Can ONLY setting Duty Cycle actuate the robot's motors? Test w/ testbench
Referenced by control_robot().
control_dumping()
void Teleop_Control::control_dumping () [inline], [private]
Teleop Dumping control.
Todo
Todo Review the dumping system w/ the team to make additions/changes & Can ONLY setting Duty Cycle actuate the robot's motors? Test w/ testbench
Referenced by control_robot().
control_mining()
void Teleop_Control::control_mining () [inline], [private]
Teleop Mining Control.
Todo
Todo Can ONLY setting Duty Cycle actuate the robot's motors? Test w/ testbench
Referenced by control_robot().
control_robot()
void Teleop_Control::control_robot () [inline], [private]
Emergency Stop functions.
Todo
Todo Make sure the estop() function is called in an appropriate place in a robot control function if needed
Wrapper that encapsulates all 3 subsystems of robotic control for teleoperation
References control_drive(), control_dumping(), and control_mining().
Referenced by callback_joy().
get_axis()
double Teleop_Control::get_axis (const JoyMsg & joy_msg, const std::initializer_list< int > & mappings) [inline], [private]
Get the axis of button pressed.
Parameters
joy_msg
mappings
Returns
double
Referenced by parse_controller_input().
get_button()
int Teleop_Control::get_button (const JoyMsg & joy_msg, const std::initializer_list< int > & mappings) [inline], [private]
Get the button pressed by XBOX Controller.
Parameters
joy_msg
mappings
Returns
int
Referenced by parse_controller_input().
parse_controller_input()
void Teleop_Control::parse_controller_input (const JoyMsg & msg) [inline], [private]
Sets XBOX controller joystick input, so this file can use it locally.
Parameters
msg
References get_axis(), and get_button().
Referenced by callback_joy().
set_param()
void Teleop_Control::set_param (const std::string & param_name, bool new_val) [inline], [private]
Sets the param argument to the intended new boolean value.
Parameters
param_name
new_val
Referenced by handle_mode_switches(), and prep_robot().
The documentation for this class was generated from the following file:
/home/jayhaych02/robotics/Lunabotics2024-ROS/src/teleop_controller/src/teleop_control.cpp